use_frameworks!

platform :ios, '8.0'

target 'RQKit_Example' do
  pod 'RQKit', :path => '../'

  target 'RQKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
